stages:
  - install
  - test
  - build



install_dependencies:
  stage: install
  image: node:22
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: node:22
  script:
    - npm test

build:
  stage: build
  image: node:22
  script:
    - npm run build || echo "No build step"
